// Generated by Apple Swift version 4.1.2 effective-3.3.2 (swiftlang-902.0.54 clang-902.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import UIKit;
@import Foundation;
@import CoreGraphics;
@import ObjectiveC;
@import Security;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PecPayment",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

/// AKMaskField is UITextField subclass which allows enter data in the fixed quantity
/// and in the certain format (credit cards, telephone numbers, dates, etc.).
/// You only need setup mask and mask template visible for the user.
/// Example of usage (programmatically):
/// \code
/// var field = AKMaskField()
/// field.setMask("{dddd}-{DDDD}-{WaWa}-{aaaa}", withMaskTemplate: "ABCD-EFGH-IJKL-MNOP")
///
/// \endcodeFor more information click here <a href="https://github.com/artemkrachulov/AKMaskField">GitHub</a>
SWIFT_CLASS("_TtC10PecPayment11AKMaskField")
@interface AKMaskField : UITextField <UITextFieldDelegate>
/// The string value that has blocks with pattern symbols that determine the certain format of input data. Wrap each mask block with proper bracket character.
/// The predetermined formats (Mask symbol : Input format):
/// <ul>
///   <li>
///     d : Number, decimal number from 0 to 9
///   </li>
///   <li>
///     D : Any symbol, except decimal number
///   </li>
///   <li>
///     W : Not an alphabetic symbol
///   </li>
///   <li>
///     a : Alphabetic symbol, a-Z
///   </li>
///   <li>
///     . : Corresponds to any symbol (default)
///   </li>
/// </ul>
/// Default value of this property is <code>nil</code>.
@property (nonatomic, copy) NSString * _Nullable maskExpression;
/// The text that represents the mask filed with replacing mask symbol by template character.
/// <ul>
///   <li>
///     1 : Template character will be copied to each mask block with repeating equal block length.
///   </li>
///   <li>
///     Equal : Template length equal to mask without brackets. Template characters will replace mask blocks in same range.
///   </li>
/// </ul>
/// Default value of this property is <code>*</code>.
@property (nonatomic, copy) NSString * _Nonnull maskTemplate;
/// Use this method to set the mask and template parameters.
/// \param mask The string value that has blocks with symbols that determine the certain format of input data.
///
/// \param maskTemplate The text that represents the mask filed with replacing mask symbol by template character.
///
- (void)setMask:(NSString * _Nonnull)mask withMaskTemplate:(NSString * _Null_unspecified)maskTemplate;
/// Set new text for the mask field. Equal to select all and paste actions.
@property (nonatomic, copy) NSString * _Nullable text;
/// Manually refresh the mask field
- (void)refreshMask;
/// Jumps to previous block when cursor is placed between brackets or before first character in current block.
@property (nonatomic) BOOL jumpToPrevBlock;
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC10PecPayment22ActivityViewController")
@interface ActivityViewController : UIViewController
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP10PecPayment29BalanceMerchantResultObserver_")
@protocol BalanceMerchantResultObserver
- (void)BalanceMerchantUpdateWithEncData:(NSString * _Nonnull)encData message:(NSString * _Nonnull)message status:(NSInteger)status;
- (void)BalanceMerchantErrorWithErrorType:(NSInteger)errorType;
@end


SWIFT_PROTOCOL("_TtP10PecPayment26BillMerchantResultObserver_")
@protocol BillMerchantResultObserver
- (void)BillMerchantUpdateWithEncData:(NSString * _Nonnull)encData message:(NSString * _Nonnull)message status:(NSInteger)status;
- (void)BillMerchantErrorWithErrorType:(NSInteger)errorType;
@end

@protocol MerchantResultObserver;
@protocol TopupMerchantResultObserver;
@class UIPresentationController;

SWIFT_CLASS("_TtC10PecPayment11InitPayment")
@interface InitPayment : NSObject <UIPopoverPresentationControllerDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)registerPayWithMerchant:(id <MerchantResultObserver> _Nonnull)merchant;
- (void)registerBillWithMerchant:(id <BillMerchantResultObserver> _Nonnull)merchant;
- (void)registerTopupWithMerchant:(id <TopupMerchantResultObserver> _Nonnull)merchant;
- (void)initPayWithToken:(NSString * _Nonnull)Token MerchantVCArg:(UIViewController * _Nonnull)MerchantVCArg TSPEnabled:(NSInteger)TSPEnabled SWIFT_METHOD_FAMILY(none);
- (void)initBillPaymentWithToken:(NSString * _Nonnull)Token MerchantVCArg:(UIViewController * _Nonnull)MerchantVCArg TSPEnabled:(NSInteger)TSPEnabled SWIFT_METHOD_FAMILY(none);
- (void)initTopupPaymentWithToken:(NSString * _Nonnull)Token MerchantVCArg:(UIViewController * _Nonnull)MerchantVCArg TSPEnabled:(NSInteger)TSPEnabled SWIFT_METHOD_FAMILY(none);
- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP10PecPayment22MerchantResultObserver_")
@protocol MerchantResultObserver
- (void)updateWithEncData:(NSString * _Nonnull)encData message:(NSString * _Nonnull)message status:(NSInteger)status;
- (void)errorWithErrorType:(NSInteger)errorType orderID:(NSInteger)orderID;
@end


SWIFT_CLASS("_TtC10PecPayment8RSAUtils")
@interface RSAUtils : NSObject
+ (NSData * _Nullable)encryptWithRSAKey:(NSData * _Nonnull)data rsaKeyRef:(SecKeyRef _Nonnull)rsaKeyRef padding:(SecPadding)padding SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)decryptWithRSAKey:(NSData * _Nonnull)encryptedData rsaKeyRef:(SecKeyRef _Nonnull)rsaKeyRef padding:(SecPadding)padding SWIFT_WARN_UNUSED_RESULT;
+ (void)deleteRSAKeyFromKeychain:(NSString * _Nonnull)tagName;
+ (SecKeyRef _Nullable)getRSAKeyFromKeychain:(NSString * _Nonnull)tagName SWIFT_WARN_UNUSED_RESULT;
+ (SecKeyRef _Nullable)addRSAPrivateKey:(NSString * _Nonnull)privkeyBase64 tagName:(NSString * _Nonnull)tagName SWIFT_WARN_UNUSED_RESULT;
+ (SecKeyRef _Nullable)addRSAPublicKey:(NSString * _Nonnull)pubkeyBase64 tagName:(NSString * _Nonnull)tagName SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)encryptWithRSAPrivateKey:(NSData * _Nonnull)data privkeyBase64:(NSString * _Nonnull)privkeyBase64 keychainTag:(NSString * _Nonnull)keychainTag SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)encryptWithRSAPublicKey:(NSData * _Nonnull)data pubkeyBase64:(NSString * _Nonnull)pubkeyBase64 keychainTag:(NSString * _Nonnull)keychainTag SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)decryptWithRSAPrivateKey:(NSData * _Nonnull)encryptedData privkeyBase64:(NSString * _Nonnull)privkeyBase64 keychainTag:(NSString * _Nonnull)keychainTag SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)decryptWithRSAPublicKey:(NSData * _Nonnull)encryptedData pubkeyBase64:(NSString * _Nonnull)pubkeyBase64 keychainTag:(NSString * _Nonnull)keychainTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UIImage;

SWIFT_CLASS("_TtC10PecPayment13SwiftOverlays")
@interface SwiftOverlays : NSObject
/// Shows <em>blocking</em> wait overlay with activity indicator, centered in the app’s main window
///
/// returns:
/// Created overlay
+ (UIView * _Nonnull)showBlockingWaitOverlay;
/// Shows wait overlay with activity indicator <em>and text</em>, centered in the app’s main window
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
+ (UIView * _Nonnull)showBlockingWaitOverlayWithText:(NSString * _Nonnull)text;
/// Shows <em>blocking</em> overlay <em>with image and text</em>,, centered in the app’s main window
/// \param image Image to be added to overlay
///
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
+ (UIView * _Nonnull)showBlockingImageAndTextOverlay:(UIImage * _Nonnull)image text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
/// Shows <em>text-only</em> overlay, centered in the app’s main window
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
+ (UIView * _Nonnull)showBlockingTextOverlay:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
/// Removes all <em>blocking</em> overlays from application’s main window
+ (void)removeAllBlockingOverlays;
+ (UIView * _Nonnull)showCenteredWaitOverlay:(UIView * _Nonnull)parentView;
+ (UIView * _Nonnull)showCenteredWaitOverlayWithText:(UIView * _Nonnull)parentView text:(NSString * _Nonnull)text;
+ (UIView * _Nonnull)showImageAndTextOverlay:(UIView * _Nonnull)parentView image:(UIImage * _Nonnull)image text:(NSString * _Nonnull)text;
+ (UIView * _Nonnull)showGenericOverlay:(UIView * _Nonnull)parentView text:(NSString * _Nonnull)text accessoryView:(UIView * _Nonnull)accessoryView horizontalLayout:(BOOL)horizontalLayout SWIFT_WARN_UNUSED_RESULT;
+ (UIView * _Nonnull)showTextOverlay:(UIView * _Nonnull)parentView text:(NSString * _Nonnull)text;
+ (UIView * _Nonnull)showProgressOverlay:(UIView * _Nonnull)parentView text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
+ (void)removeAllOverlaysFromView:(UIView * _Nonnull)parentView;
+ (void)updateOverlayText:(UIView * _Nonnull)parentView text:(NSString * _Nonnull)text;
+ (void)updateOverlayProgress:(UIView * _Nonnull)parentView progress:(float)progress;
+ (void)showAnnoyingNotificationOnTopOfStatusBar:(UIView * _Nonnull)notificationView duration:(NSTimeInterval)duration animated:(BOOL)animated;
+ (void)closeAnnoyingNotificationOnTopOfStatusBar:(id _Nonnull)sender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10PecPayment27TopupMerchantResultObserver_")
@protocol TopupMerchantResultObserver
- (void)TopupMerchantUpdateWithEncData:(NSString * _Nonnull)encData message:(NSString * _Nonnull)message status:(NSInteger)status;
- (void)TopupMerchantErrorWithErrorType:(NSInteger)errorType;
@end




@interface UIImageView (SWIFT_EXTENSION(PecPayment))
- (void)imageFromUrl:(NSString * _Nonnull)urlString;
@end


@interface UIViewController (SWIFT_EXTENSION(PecPayment))
/// Shows wait overlay with activity indicator, centered in the view controller’s main view
/// Do not use this method for <em>UITableViewController</em> or <em>UICollectionViewController</em>
///
/// returns:
/// Created overlay
- (UIView * _Nonnull)showWaitOverlay;
/// Shows wait overlay with activity indicator <em>and text</em>, centered in the view controller’s main view
/// Do not use this method for <em>UITableViewController</em> or <em>UICollectionViewController</em>
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
- (UIView * _Nonnull)showWaitOverlayWithText:(NSString * _Nonnull)text;
/// Shows <em>text-only</em> overlay, centered in the view controller’s main view
/// Do not use this method for <em>UITableViewController</em> or <em>UICollectionViewController</em>
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
- (UIView * _Nonnull)showTextOverlay:(NSString * _Nonnull)text;
/// Shows overlay with text and progress bar, centered in the view controller’s main view
/// Do not use this method for <em>UITableViewController</em> or <em>UICollectionViewController</em>
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
- (UIView * _Nonnull)showProgressOverlay:(NSString * _Nonnull)text;
/// Shows overlay <em>with image and text</em>, centered in the view controller’s main view
/// Do not use this method for <em>UITableViewController</em> or <em>UICollectionViewController</em>
/// \param image Image to be added to overlay
///
/// \param text Text to be shown on overlay
///
///
/// returns:
/// Created overlay
- (UIView * _Nonnull)showImageAndTextOverlay:(UIImage * _Nonnull)image text:(NSString * _Nonnull)text;
/// Shows notification on top of the status bar, similar to native local or remote notifications
/// \param notificationView View that will be shown as notification
///
/// \param duration Amount of time until notification disappears
///
/// \param animated Should appearing be animated
///
+ (void)showNotificationOnTopOfStatusBar:(UIView * _Nonnull)notificationView duration:(NSTimeInterval)duration animated:(BOOL)animated;
/// Removes all overlays from view controller’s main view
- (void)removeAllOverlays;
/// Updates text on the current overlay.
/// Does nothing if no overlay is present.
/// \param text Text to set
///
- (void)updateOverlayText:(NSString * _Nonnull)text;
/// Updates progress on the current overlay.
/// Does nothing if no overlay is present.
/// \param progress Progress to set 0.0 .. 1.0
///
- (void)updateOverlayProgress:(float)progress;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
